import "./globals.css";
import Header from "@/components/layout/Header";
import CartDrawer from "@/components/cart/CartDrawer";
import { Toaster } from "@/components/ui/sonner";
import Providers from "@/components/Providers";

import { NextIntlClientProvider } from "next-intl";
import { getMessages , getLocale } from 'next-intl/server'
import { notFound } from 'next/navigation'


const locales = ["en" , "fr"]

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({ children , params }) {

    const { locale } = await params

    if (!locales.includes(locale)) notFound()

     const messages = await getMessages()   
  return (
    <html lang={locale}>
      <body
        className={`antialiased`}
      >
        <NextIntlClientProvider locale={locale} messages={messages}>
            <Providers>
                <Header />
                <CartDrawer />
                {children}
            </Providers>
        </NextIntlClientProvider>
        <Toaster />
      </body>
    </html>
  );
}
